/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import UnionImage from 'src/assets/images/Desktop1_Union.png';
import IntersectImage from 'src/assets/images/Desktop1_Intersect.png';
import Ellipse194Image from 'src/assets/images/Desktop1_Ellipse_194.png';
import Ellipse196Image from 'src/assets/images/Desktop1_Ellipse_196.png';
import Ellipse195Image from 'src/assets/images/Desktop1_Ellipse_195.png';
import SubtractImage from 'src/assets/images/Desktop1_Subtract.png';
import { styled } from '@mui/material/styles';

const Desktop11 = styled('div')({
  backgroundColor: `rgba(0, 0, 0, 0)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `2526px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
});

const Group36707 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `60px`,
  height: `54.55px`,
  left: `90px`,
  top: `109px`,
});

const Union = styled('img')({
  height: `39.44px`,
  width: `60px`,
  position: `absolute`,
  left: `0px`,
  top: `-39px`,
});

const Intersect = styled('img')({
  height: `32.84px`,
  width: `22.86px`,
  position: `absolute`,
  left: `19px`,
  top: `-7px`,
});

const Ellipse194 = styled('img')({
  height: `12.17px`,
  width: `11.75px`,
  position: `absolute`,
  left: `0px`,
  top: `-55px`,
});

const Ellipse196 = styled('img')({
  height: `12.17px`,
  width: `11.75px`,
  position: `absolute`,
  left: `24px`,
  top: `-55px`,
});

const Ellipse195 = styled('img')({
  height: `12.17px`,
  width: `12.17px`,
  position: `absolute`,
  left: `47px`,
  top: `-55px`,
});

const HelpPeopleDonateMone = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `600`,
  fontSize: `45px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `653px`,
  height: `273px`,
  position: `absolute`,
  left: `90px`,
  top: `339px`,
});

const Q140 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `600`,
  fontSize: `25px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `79px`,
  height: `36px`,
  position: `absolute`,
  left: `98px`,
  top: `682px`,
});

const Q27 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `600`,
  fontSize: `25px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `34px`,
  position: `absolute`,
  left: `289px`,
  top: `682px`,
});

const Q3 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `600`,
  fontSize: `25px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `34px`,
  position: `absolute`,
  left: `466px`,
  top: `682px`,
});

const Hours = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 0.45)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `600`,
  fontSize: `15px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `48px`,
  height: `23px`,
  position: `absolute`,
  left: `90px`,
  top: `659px`,
});

const Designer = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 0.45)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `600`,
  fontSize: `15px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `73px`,
  height: `23px`,
  position: `absolute`,
  left: `410px`,
  top: `659px`,
});

const Screens = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 0.45)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `600`,
  fontSize: `15px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `79px`,
  height: `23px`,
  position: `absolute`,
  left: `250px`,
  top: `659px`,
});

const DonationAppUxCaseStu = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `500`,
  fontSize: `30px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `547px`,
  height: `43px`,
  position: `absolute`,
  left: `90px`,
  top: `296px`,
});

const ShareSupport = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `700`,
  fontSize: `30px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `282px`,
  height: `43px`,
  position: `absolute`,
  left: `165px`,
  top: `73px`,
});

const Subtract = styled('img')({
  height: `872px`,
  width: `434px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `880px`,
  top: `176px`,
});

const ProjectPrompt = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `600`,
  fontSize: `40px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `334px`,
  height: `55px`,
  position: `absolute`,
  left: `177px`,
  top: `1042px`,
});

const Background = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `600`,
  fontSize: `40px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `278px`,
  height: `46px`,
  position: `absolute`,
  left: `839px`,
  top: `892px`,
});

const Solution = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `600`,
  fontSize: `40px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `212px`,
  height: `46px`,
  position: `absolute`,
  left: `839px`,
  top: `1127px`,
});

const Challenges = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `600`,
  fontSize: `40px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `278px`,
  height: `46px`,
  position: `absolute`,
  left: `839px`,
  top: `1023px`,
});

const Introduction = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 0.45)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `600`,
  fontSize: `25px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `176px`,
  position: `absolute`,
  left: `839px`,
  top: `955px`,
});

const Introduction1 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 0.45)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `600`,
  fontSize: `25px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `176px`,
  position: `absolute`,
  left: `839px`,
  top: `1184px`,
});

const Introduction2 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 0.45)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `600`,
  fontSize: `25px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `176px`,
  position: `absolute`,
  left: `839px`,
  top: `1086px`,
});

const Rectangle2 = styled('div')({
  backgroundColor: `rgba(217, 217, 217, 1)`,
  width: `1318px`,
  height: `666px`,
  position: `absolute`,
  left: `77px`,
  top: `1527px`,
});

function Desktop1(props) {
  return (
    <Desktop11 className={props.className}>
      <Group36707>
        <Union src={UnionImage} loading="lazy" alt={'Union'} />
        <Intersect src={IntersectImage} loading="lazy" alt={'Intersect'} />
        <Ellipse194 src={Ellipse194Image} loading="lazy" alt={'Ellipse 194'} />
        <Ellipse196 src={Ellipse196Image} loading="lazy" alt={'Ellipse 196'} />
        <Ellipse195 src={Ellipse195Image} loading="lazy" alt={'Ellipse 195'} />
      </Group36707>
      <HelpPeopleDonateMone>
        {`Help people, donate money and make the world a better place!`}
      </HelpPeopleDonateMone>
      <Q140>{`+140`}</Q140>
      <Q27>{`27`}</Q27>
      <Q3>{`3`}</Q3>
      <Hours>
        {`Hours
`}
      </Hours>
      <Designer>{`Designer`}</Designer>
      <Screens>{`Screens`}</Screens>
      <DonationAppUxCaseStu>
        {`Donation App UX case study`}
      </DonationAppUxCaseStu>
      <ShareSupport>{`Share Support`}</ShareSupport>
      <Subtract src={SubtractImage} loading="lazy" alt={'Subtract'} />
      <ProjectPrompt>{`Project Prompt`}</ProjectPrompt>
      <Background>{`Background`}</Background>
      <Solution>{`Solution`}</Solution>
      <Challenges>{`Challenges`}</Challenges>
      <Introduction>{`Introduction`}</Introduction>
      <Introduction1>{`Introduction`}</Introduction1>
      <Introduction2>{`Introduction`}</Introduction2>
      <Rectangle2></Rectangle2>
    </Desktop11>
  );
}

export default Desktop1;
